on:
  repository_dispatch:
    types: [reliza-build-event]

name: Publish

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    env:
      IMAGE_NAMESPACE: ${{ secrets.IMAGE_NAMESPACE }}
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build for all different OS and Architecture
        run: docker build -f Dockerfile.exec -t $IMAGE_NAMESPACE/$IMAGE_NAME:latest .